### ISSUE TITLE
Load an fxml from a string

### ISSUE THREAD

**Issue by TKPGitHub** [edvin/tornadofx-guide#107]
Hi Edvin,
Is there a way to load an fxml from a STRING ?
The documentation only mentions: override val root : BorderPane by fxml() or by fxml("path_to_fxml_file")

How about writting something like this: override val root : BorderPane by fxml(ByteArrayInputStream(FXML_STRING.getBytes()))

The reason of my request i have my fxml files are stored in the database.

Found a javafx solution from https://stackoverflow.com/questions/16548925/how-to-load-fxml-from-string-in-javafx :
FXMLLoader loader = new FXMLLoader();
AnchorPane layout = (AnchorPane) loader.load(
  new ByteArrayInputStream(FXML_STRING.getBytes())
);

Thks

**Comment by edvin** [comment]
Hi,

I've just committed support for loading FXML from an InputStream. Does that cover your use case? :)

**Comment by TKPGitHub** [comment]
Hi Edvin,
Impressively quick! 
Yes, I've seen in your implementation in Component.kt (line 1127 ..1140) if I'm not wrong.
Thanks
Cheers
