### ISSUE TITLE
Complex Nested Model Advice

### ISSUE THREAD

**Issue by AustinShalit** [edvin/tornadofx-guide#121]
Hi! I have a situation and I wasn't sure what the best way to handle it is using TornadoFX. I am going to simplify the problem a bit.

I have a backend data class called Job. For simplicity sake, a job has a name and a options class but in actuality is much more complex:
```
data class Job(
    val name: String,
    val options: Options
)

data class Options(
        val firstOption: Double, 
        val secondOption: Double
)
```

Now is when I start to get confused about what to do but this is what I have attempted:

I have a data transfer object to wrap the backend data into JavaFX properties & accompanying ItemViewModel.
```
data class JobDto(val job: Job) {
    val nameProperty = SimpleStringProperty(job.name)
    var name by nameProperty

    val optionsProperty = SimpleObjectProperty(job.options)
    var options by optionsProperty
}

class JobModel : ItemViewModel<JobDto>() {
    val name = bind(JobDto::nameProperty)
    val options = bind(JobDto::optionsProperty)
}
```

And the fragment:
```
class JobConfiguration : Fragment() {
    private val job by inject<JobModel>()

    override val root = form {
        field("Name") {
            textfield(job.name)
        }
        fieldset("Options") {
            field("First") {
                textfield(job.options) // What do I put here?
            }
            field("Second") {
                textfield(job.options) // What do I put here?
            }
        }
    }
}
```

Any advice is appreciated.

**Comment by Octogonapus** [comment]
Here is a minimal example that reproduces the behavior we are getting. Basically, we want to get this application to work: https://pastebin.com/KTxYPFii

I should also note that we are using JDK 13 and the latest tornadofx v2 snapshot.
