### ISSUE TITLE
Numbering Diagrams and Pictures

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-guide#2]
I usually do this later as the structure fleshes out. But Section 2 is starting to solidify in its structure so I'm going to go back and number all the diagrams and pictures. This is necessary for published material to be more readable and traceable. 

Example of how a picture/diagram should be labeled is below.

![](https://camo.githubusercontent.com/21d91e000f36556b67bea322ff1152199aee483e/68747470733a2f2f692e696d6775722e636f6d2f41474d435038532e706e67)

**Comment by edvin** [comment]
OK, Great! Should I do the same when I add images to the wiki, or is it only necessary in the guide?

**Comment by thomasnield** [comment]
You can do it in the Wiki if you like, but I don't think it is necessary. It usually is critical for material with lengthy content or may get printed, and images get moved around to fit on paper and the author can refer to diagram numbers in the text.

**Comment by edvin** [comment]
OK, probably not neded in the Wiki then :) Thanks!
