### ISSUE TITLE
What's the process of migrating wiki pages to the guide

### ISSUE THREAD

**Issue by nimakro** [edvin/tornadofx-guide#28]
Like the title indicates, I was wondering how the process is, on migrating wiki-pages/infos to the guide.
Are we deleting the page if we migrated all parts of the specific page?

**Comment by edvin** [comment]
We delete the page and change the link in the index to the guide until all the pages are replaced, then we simply link to the guide on the front page of the wiki and delete all the sub pages.

**Comment by nimakro** [comment]
Oky sounds good, will do that then.

**Comment by edvin** [comment]
Thank you. Your contributions and help these past weeks have been invaluable 👏
