### ISSUE TITLE
vboxconstraints and hboxconstraints wrong

### ISSUE THREAD

**Issue by thomasnield** [edvin/tornadofx-guide#3]
Should be this: 

```kotlin
vbox {
    button("Button 1") { 
        vboxConstraints {
            marginRight = 20.0
            vGrow = Priority.ALWAYS
        }
    }
    button("Button 2")
}
```

Not this: 

```kotlin
vbox {
    vboxConstraints {
        marginRight = 20.0
        vGrow = Priority.ALWAYS
    }
    button("Button 1")
    button("Button 2")
}
```

**Comment by thomasnield** [comment]
Resolved

**Comment by toplinuxsir** [comment]
how to specify the vbox add order ?

**Comment by edvin** [comment]
AFAIK, you specify the order by the index in the children list. Simply add them in the order you want them in or rearrange the list :)

**Comment by toplinuxsir** [comment]
How to ?
Can you show me examples ?
Thanks !

**Comment by edvin** [comment]
Maybe we are talking past each other, but you control the children order by adding them in the order you want. So if you want `Button 2` to appear before `Button 1`, you would simply add them in that order:

```kotlin
button("Button 2")
button("Button 1")
```
