### ISSUE TITLE
multiple stylesheets

### ISSUE THREAD

**Issue by nihiluis** [edvin/tornadofx-guide#47]
in css I like to split my css to multiple files, like style.css for generla stuff and component.css for a specific component. (for a better overview)

i'd like to do something similar in tfx.

i have this as my main stylesheet
```kotlin
class Styles : Stylesheet() {...}
```
how do I load something like this? I dont want to have all the stuff in one big Styles class

```kotlin
class FooterStyle : Stylesheet() {
    companion object {
        val footer by cssclass()
        val links by cssclass()
    }

    init {
        footer {
            links {
                fontSize = 10.px
            }
        }
    }
}
```

**Comment by nihiluis** [comment]
probs like this?

```kotlin
    override fun start(stage: Stage) {
        importStylesheet(Styles::class)
importStylesheet(FooterStyle::class)
        super.start(stage)
        loginController.init()
}
```
correct me if im wrong please

**Comment by edvin** [comment]
To load multiple stylesheets, just add them as parameters to your `App` class, no need to import them manually:

```kotlin
class MyApp : App(MainView::class, Styles::class, FooterStyles::class)
```

You can also split declarations into multiple files and load them as one stylesheet, but I don't really see a use case for it, so I won't provide an example. What you might want to do though, is to add all your `cssclass` definitions to `Styles` and then configure the selectors in different stylesheets. This way you avoid the overhead of having to know what stylesheet a class is defined in when you're adding classes to nodes etc.
