### ISSUE TITLE
Imageview(local image source/url) NOT found exception

### ISSUE THREAD

**Issue by Yadarma** [edvin/tornadofx-guide#49]
I am trying to create imageview when I do with online url e.g.  "https://github.com/image.png" it works but not when I load the image locally from resources like "res/image.png" ?

Thanks for the great library.

**Comment by nimakro** [comment]
Hey @Yadarma could you give some more detail on how you are using the `ImageView` and how your resource structure looks like.
Just as a side note, for future issues regarding TornadoFX you should use the tornadofx repo. This repo should be used for issues regarding the guide.

**Comment by Yadarma** [comment]
```
 override val root = hbox {
        imageview("res/image.png")
        separator(Orientation.VERTICAL) { }
        form {}
```
```
src
	main
		kotlin
			x.y
				view
					view.kt

		res
			image.png
```
A side note, I tried every/all level of hierarchy.

**Comment by edvin** [comment]
You need to create `src/main/resources` for resources you want to put on the class path. Files put directly in `src/main/resources` will be accessible as `/filename`. The physical path for `res/image.png` would therefore be `src/main/resources/res/image.png`. This is the default for both Maven and Gradle, and has nothing to do with TornadoFX or JavaFX/ImageView for that matter :) If you check your build folder right now you'll simply see that the res folder wasn't even included there.

**Comment by Yadarma** [comment]
Hey @edvin . After removing "res" folder, creating "src/main/resources" as resources and adding "image.png" still the same exception 
`java.lang.IllegalArgumentException: Invalid URL: Invalid URL or resource not found
	at javafx.scene.image.Image.validateUrl(Image.java:1118)`  
using "image.png", "/image.png" or "src/main/resources/image.png"

**Comment by edvin** [comment]
You don't even need to run your application until you have verified that the build system indeed copies the file to the correct folder. If you place the file in `src/main/resources/image.png` and rebuild your project, you can verify that the file is copied to `target/classes/image.png`. You should then be able to reference it as `/image.png`. Try to run your build system from the command line and then check the target folder. If this doesn't work, post the link to your project :)

**Comment by Yadarma** [comment]
Thanks dear @edvin  for your so much informative help. I found out there is maybe an "Intellij gradle kotlin bug" copying resources to the `target/classes/` dir So, I used this gradle task as a workaround:
```
task copyResources(type: Copy) {
    from "src/main/resources"
    into "out/production/classes"
}
processResources.dependsOn copyResources
```
Again Thanks for your so much for your great TornadoFX. Appreciated 👍

**Comment by edvin** [comment]
No problem - There might indeed be a bug here - as far as I know, `out/production/classes` is NOT the default output location for a Gradle based project. You should try to re-import the project and see if that fixes the output location. Try doing a `gradlew build` from the command line and see where the project is built. IDEA should honor this location.

**Comment by Yadarma** [comment]
01 - (Using TornadoFX project/plugin in Intellij IDEA) It seems to me it's NOT pure gradle project or even half of it. There is no gradlew file or other gradle files except for the the build file. Under the hood it's controlled mainly by the IDEA .iml files see this
```
<?xml version="1.0" encoding="UTF-8"?>
<module external.linked.project.id="Prep:main" external.linked.project.path="$MODULE_DIR$/../.." external.root.project.path="$MODULE_DIR$/../.." external.system.id="GRADLE" external.system.module.group="" external.system.module.type="sourceSet" external.system.module.version="unspecified" type="JAVA_MODULE" version="4">
  <component name="FacetManager">
    <facet type="kotlin-language" name="Kotlin">
      <configuration version="3" platform="JVM 1.8" useProjectSettings="false">
        <compilerSettings />
        <compilerArguments>
          <option name="destination" value="$MODULE_DIR$/../../build/classes/kotlin/main" />
          <option name="noStdlib" value="true" />
          <option name="noReflect" value="true" />
          <option name="moduleName" value="Prep" />
          <option name="jvmTarget" value="1.8" />
          <option name="addCompilerBuiltIns" value="true" />
          <option name="loadBuiltInsFromDependencies" value="true" />
          <option name="languageVersion" value="1.2" />
          <option name="apiVersion" value="1.2" />
          <option name="pluginOptions">
            <array />
          </option>
          <option name="pluginClasspaths">
            <array />
          </option>
        </compilerArguments>
      </configuration>
    </facet>
  </component>
  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_8">
    <output url="file://$MODULE_DIR$/../../out/production/classes" />
    <exclude-output />
    <content url="file://$MODULE_DIR$/../../src/main">
      <sourceFolder url="file://$MODULE_DIR$/../../src/main/java" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/../../src/main/kotlin" isTestSource="false" />
      <sourceFolder url="file://$MODULE_DIR$/../../src/main/resources" type="java-resource" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
```
02 - After building using task build gradle, png file was NOT copied to any folder at all in the project & gen classes are only in `out/production/classes`
