### ISSUE TITLE
Replace Raw JavaFX Code with Builders in Components Page

### ISSUE THREAD

**Issue by bekwam** [edvin/tornadofx-guide#58]
On the Components Page (3), an example is given using JavaFX object creation. The example hints at a builder notation that isn't presented for several topics.  When the builder notation is presented, it's of a different example and the improvement is less clear.

The builders are the preferred way to write TornadoFX code and beginners might not have the JavaFX background to make an intermediary step worthwhile.

**Comment by edvin** [comment]
Fixed :)
