### ISSUE TITLE
Drag and Drop with TreeView

### ISSUE THREAD

**Issue by sp33dy** [edvin/tornadofx-guide#85]
Hi,

Not a bug, but more of a question as to whether Drag and Drop is possible with tree items? I need to be able to rearrange nodes in the heirarchy.

I've recently tested Kotlin and Tornadofx and am extremely impressed. I come from a Java Swing background, so I'm loving the way this technology stack makes every so much easier. However, before I can commit to moving over to it with a Client's app, I need to implement this same function. 

I can only find the odd article and I'm too new to know whether any of the articles are possible. I.E. the closest I think I can find is somehow stepping back to JavaFX and using its capability. Is that true?

Any thoughts or pointers would be appreciated.

Kind regards

Carl

**Comment by edvin** [comment]
Hi! An important thing to note about TornadoFX is that it is "just" a higher level API on top of JavaFX, but it never hides the JavaFX API, so you can always fall back to the JavaFX way of doing things. In fact, many features of JavaFX doesn't make sense to improve, so the right way might just be to use them, though with Kotlin syntax.

That said, TornadoFX doesn't have any special support for rearranging tree items using DND, but it's not hard to do. Search for "JavaFX TreeView reorder items with drag and drop" and you'll find plenty of information. The most straight forward way of doing it would be to implement a cell factory and return a custom cell where you have configured at least `onDragDetected` and `onDragDropped`.

I'm pressed for time these days, but if you implement a nice solution and post it here, I'd be happy to generalize it and include it in the framework :)

**Comment by sp33dy** [comment]
Edvin,

Thanks for responding as it is the 'steer' that I was looking for. I'm new
to JavaFX so need to do a little more reading, but the google terms you
provided has led me to what I need. I'll take time over the next few weeks
to explore this and will submit my findings, if and when I have them.

Kind regards

Carl

**Comment by edvin** [comment]
Great! Looking forward to it :)

**Comment by ahinchman1** [comment]
Hey @sp33dy - there's some good material out there on javafx drag and drop - https://examples.javacodegeeks.com/desktop-java/javafx/event-javafx/javafx-drag-drop-example/ and also, it might be helpful for you to take a look at the OSGI.kt in the TornadoFX project.  

Cheers!

**Comment by sp33dy** [comment]
Wow, many thanks Amanda. Can't believe I've had several responses so
quickly. Will take a look and build from it.

Thank you.

**Comment by sp33dy** [comment]
Close, ever so close! ...but alas, no cigar.

Any chance you can help me with my last problem? 

Here's what I've got to (MyDnDTreepApp):

`
package tutorial.dragndrop

import tornadofx.App
import tornadofx.launch

class MyDnDTreeApp: App(MyJFXView::class) {
}

fun main(args: Array<String>) {
	launch<MyDnDTreeApp>(args)
}
`

and the View (MyJFXView):

`
package tutorial.dragndrop

import javafx.scene.control.TreeCell
import javafx.scene.control.TreeItem
import javafx.scene.control.cell.TextFieldTreeCell
import javafx.scene.input.ClipboardContent
import javafx.scene.input.DataFormat
import javafx.scene.input.TransferMode
import javafx.scene.layout.HBox
import tornadofx.View
import tornadofx.cellFormat
import tornadofx.populate
import tornadofx.treeview
import tutorial.data.Person
import tutorial.data.departments
import tutorial.data.persons
import javafx.scene.Node

class MyJFXView : View() {
	
	override val root = HBox()
	
	init {
		with(root) {
			treeview<Person> {
				
				val DATA_FORMAT_PERSON = DataFormat("Person")
				val DATA_FORMAT_INDEX = DataFormat("Index")
				
				val DROP_HINT_STYLE = "-fx-border-color: #eea82f; -fx-border-width: 0 0 2 0; -fx-padding: 3 3 1 3"
				
			    // Create root item
			    root = TreeItem(Person("Departments", ""))
				
				setShowRoot(false)

			    // Make sure the text in each TreeItem is the name of the Person
			    cellFormat { text = it.name }
			
			    // Generate items. Children of the root item will contain departments
			    populate { parent ->
			        if (parent == root) departments else persons.filter { it.department == parent.value.name }
			    }
				
			    setCellFactory {
					object : TextFieldTreeCell<Person>() {
						init {							
							setOnDragDetected {
								event -> run {
									var db = startDragAndDrop(TransferMode.MOVE)
									var content = ClipboardContent()
									content.put(DATA_FORMAT_PERSON, getItem())
									content.put(DATA_FORMAT_INDEX, getIndex())
									db.setContent(content)
									db.setDragView(snapshot(null, null))       
									event.consume()
								}
							}
							setOnDragOver {
								event -> run {
									if (event.getDragboard().hasContent(DATA_FORMAT_PERSON)) {
										event.acceptTransferModes(TransferMode.MOVE);
									}
								}
							}
							setOnDragEntered {
								event -> run {
									setStyle(DROP_HINT_STYLE)
								}
							}
							setOnDragExited {
								event -> run {
									setStyle("")
								}
							}
							setOnDragDropped {
								event -> run {
									if (event.getDragboard().hasContent(DATA_FORMAT_PERSON)) {
										var index = event.getDragboard().getContent(DATA_FORMAT_INDEX) as Int
										var dragItem = getTreeItem(index) as TreeItem<Person>
										dragItem.getParent().getChildren().remove(dragItem)
										
//										getChildren().add(dragItem)
										
										event.setDropCompleted(true)
									}
								}
							}
						}
					}
				}
			}
		} 
	}
}
`

You'll find the dragging of a Person starts, highlights where it will drop and accepts the drop (by removing the item from the ObservableList).

However, all I get are code errors when I try to add the tree item to the list, i.e. uncomment out the getChildren().add(dragItem)

I end up with the following compilation error:

>Type mismatch: inferred type is TreeItem but @IDProperty Node! was expected

I can't figure out what I have to do to cast it to this Node object! I've tried casting to TreeItem, TextFieldTreeCell and raft of other things.

How do I simply add a new item to the list so that the Observable list reflects it in the TreeView? Any idea?

I know I'm really close to what I need. There are things I can change, such as I send the index of the item to be removed, because I don't like keeping a local variable that some examples have. I.E. When drag starts, they rely on a local copy of the treeitem rather than what is passed in the clipboard, which in my view, is a better way to do it.

Any thoughts or help would be really appreciated

**Comment by sp33dy** [comment]
Aha! 

> getTreeItem().getParent().getChildren().add(dragItem)

I needed to use the getTreeItem() and work from there.

Right, fundamentally, this is now working, but I need to fix a few issues with the dropping; i.e. depending on whether I land on a Division (grouping) or a child, I need the drop to do one of two different things.

However, I'll leave this in here for now, for anyone else interested. I'm sure others have done this, but I've not found a reference point.

**Comment by ahinchman1** [comment]
I'll take a look at this sometime tonight or tomorrow!

**Comment by edvin** [comment]
Short answer: You're targeting the wrong children list, you want the children list of the current treeItem for the drop operation, so change your uncommented line to:

```kotlin
treeItem.parent.children.add(dragItem)
```

.. and you're good to go.

However, instead of manipulating and creating TreeItem instances manually, you should operate on and return observable lists from the populate function. That way you just need to manipulate the hierarchy, and everything will update automatically.

**Comment by edvin** [comment]
PS: You have littered your code with `run {}` block, but they have no effect. What did you try to achieve with those?

**Comment by edvin** [comment]
Here is a more optimized version using sealed classes. This allows you to manipulate far less on the UI elements, and more on your data objects instead. It also makes your code a lot more readable and maintainable IMO :)

```kotlin
package tutorial.dragndrop

import javafx.collections.FXCollections
import javafx.collections.ObservableList
import javafx.scene.control.TreeItem
import javafx.scene.control.cell.TextFieldTreeCell
import javafx.scene.input.ClipboardContent
import javafx.scene.input.DataFormat
import javafx.scene.input.TransferMode
import tornadofx.*
import java.util.*
import tutorial.dragndrop.HREntity.Department
import tutorial.dragndrop.HREntity.Person

sealed class HREntity(val name: String) {
    val id = UUID.randomUUID()

    override fun toString() = name

    class Person(name: String) : HREntity(name)

    class Department(name: String, people: List<Person>? = emptyList()) : HREntity(name) {
        val people: ObservableList<HREntity> = FXCollections.observableArrayList<HREntity>(people)
    }
}

val departments = listOf(
        Department("Marketing",
                listOf(
                        Person("Mary Hanes"),
                        Person("Erin James")
                )
        ),
        Department("Customer Service",
                listOf(
                        Person("Steve Folley"),
                        Person("Erlick Foyes"),
                        Person("Larry Cable")
                )
        ),
        Department("Help Desk",
                listOf(
                        Person("John Ramsey"),
                        Person("Jacob Mays")
                )
        )
).observable()

class MyJFXView : View() {
    companion object {
        val DATA_FORMAT_PERSON_ID = DataFormat("PersonId")
        val DATA_FORMAT_INDEX = DataFormat("Index")

        val DROP_HINT_STYLE = "-fx-border-color: #eea82f; -fx-border-width: 0 0 2 0; -fx-padding: 3 3 1 3"
    }

    override val root = treeview<HREntity> {
        // Create root item
        root = TreeItem(Department("Departments"))

        isShowRoot = false

        // Make sure the text in each TreeItem is the name of the Person
        cellFormat { text = it.name }

        // Root is departments, else list children of the current Person
        populate { parent ->
            if (parent == root) departments else (parent.value as? Department)?.people
        }

        setCellFactory {
            object : TextFieldTreeCell<HREntity>() {
                init {
                    setOnDragDetected { event ->
                        run {
                            val db = startDragAndDrop(TransferMode.MOVE)
                            val content = ClipboardContent()
                            content[DATA_FORMAT_PERSON_ID] = item.id
                            content[DATA_FORMAT_INDEX] = index
                            db.setContent(content)
                            db.dragView = snapshot(null, null)
                            event.consume()
                        }
                    }
                    setOnDragOver { event ->
                        if (event.dragboard.hasContent(DATA_FORMAT_PERSON_ID)) {
                            event.acceptTransferModes(TransferMode.MOVE)
                        }
                    }
                    setOnDragEntered { event ->
                        event.isAccepted
                        style = DROP_HINT_STYLE
                    }
                    setOnDragExited { _ ->
                        style = ""
                    }
                    setOnDragDropped { event ->
                        if (event.dragboard.hasContent(DATA_FORMAT_PERSON_ID)) {
                            val index = event.dragboard.getContent(DATA_FORMAT_INDEX) as Int
                            val dragItem = getTreeItem(index) as TreeItem<Person>

                            val person = dragItem.value
                            val sourceDepartment = dragItem.parent.value as Department
                            val targetDepartment = treeItem.parent.value as Department

                            sourceDepartment.people.remove(person)
                            targetDepartment.people.add(person)
                            
                            event.isDropCompleted = true
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by sp33dy** [comment]
I feel deeply humbled by the fact you've taken time to provide help. I'm a
long time (Java v1) developer who just picked up Kotlin and TornadoFX last
Thursday! I desperately needed to know if I could get the TreeView Drag and
Drop working so that I could port a Client's application over to this new
world. I can't believe how great the technology is!

You are correct in that there were things I put into my original solution
because I just didn't know any better (i.e. the Run() clause, as I ran
across them in a few google articles). I also stumbled over the 'populate'
function (in the tutorials I'd read, it hadn't stood out).

I really appreciate your new example and shall run it later tonight (at a
client site this morning, so can't test it).

When I clicked into GitHub, I see your answers aren't in the follow-up
posts. Is that normal when responding via email? IF so, I'd like to paste
your example in and then close the item.

...again, many many thanks for the assistance and for producing a brilliant
package. I'm going to be able to reduce many days worth of work into hours!
I just can't believe how good this is (I should have invested time in the
past to look into these things).

Kind regards

Carl

**Comment by edvin** [comment]
My pleasure. I try to help out as much as I can, though I've been a bit busy with other stuff lately. Getting back into it though :)

By the way, do you plan on putting something on the clipboard? You could remove the clipboard code if you just want to do drag and drop.

It looks like my answers and code are all here on the issue, not sure what you believe is missing?

**Comment by sp33dy** [comment]
Good morning,

There must have been a browser problem when I checked this ticket yesterday. It's now showing all the content. I'll close it.

Before I do, is there somewhere you guys hang-out online for questions? Rather than raising them here?

I'm now in full migration mode and am struggling with one other issue. I've a Combobox that I'm trapping onChange and want to remove fields from a fieldset. When I use whenVisible, it hides them, but there is white space left (i.e. the fields physically disappear but the rendering seems to leave their position). Given I'm basically trying to drive two different forms from the one combo, I'm wondering what the strategy would be to achieve this, i.e. have two views and swap one or the other in/out based on the combobox selection, continue with the whenVisible option or something else...   finding a group of like minded people might help me get an answer.

However, I wish again to say thank you and will close this ticket as resolved. The example works really well and I've now learnt many more things from it.

**Comment by gtnarg** [comment]
There is a very active and friendly slack group (link on the top right of
https://tornadofx.io/)

Grant

**Comment by sp33dy** [comment]
Hi Grant,

I tried that link, but it requires me to have a jetbrains.com account. I
already have a slack account and use the desktop version for chatting to
friends. The one instance where I've connected to a Slack channel for a
usergroup, they sent me a link that connected me. So I assumed that given I
can't see a way to register without JetBrains, that the link didn't work.
What should I do?

Kind regards
Carl

**Comment by edvin** [comment]
Send me your email and I'll send you an invite :)

**Comment by sp33dy** [comment]
carl.speed@gmail.com   I'll edit this out shortly. :)

**Comment by edvin** [comment]
Got it!

**Comment by ahinchman1** [comment]
Hey @sp33dy there's also the KotlinLang slack and we hang out on the TornadoFX channel!
