### ISSUE TITLE
Drawer tag in fxml problem

### ISSUE THREAD

**Issue by ysdxz207** [edvin/tornadofx-guide#91]
When I use Drawer tag in fxml,idea tell me "Unable to instantiate".
Please help me.

```

<VBox>
                    <padding>
                        <Insets top="4"/>
                    </padding>
                    <Drawer>
                        <items>
                            <TextArea fx:id="textAreaValue" minHeight="444" minWidth="610" prefWidth="610"/>
                        </items>
                    </Drawer>
                </VBox>

```
![_20181121173420](https://user-images.githubusercontent.com/4596561/48833073-8faad080-edb5-11e8-8d0c-36d10a933505.png)

**Comment by edvin** [comment]
The Drawer control was not made with FXML support in mind. If you look at the code you'll see that it requires some constructor parameters. It might be possible to instantiate with constructor parameters in FXML, but I don't use FXML and have no interest in it so I'm not sure how that would be done.

I can't see a single good reason to use FXML in 2018 so I would recommend you reconsider this approach and go for the type safe builders instead. You won't regret it :)

**Comment by ysdxz207** [comment]
I will adopt your suggestion, thank you very much.
